version: '3.4'

services:
  develop:
    build: ./
    container_name: develop
    environment:
      FLASK_ENV: development
      FLASK_APP: app/main
    ports:
      - "${PORT}:80"
    volumes:
      - "${PWD}:/app"
    command: flask run --host=0.0.0.0 --port 80
